### ISSUE TITLE
Doesn't appear to capture running video correctly

### ISSUE THREAD

**Issue by wookelvin** [negativetwelve/react-native-ux-cam#44]
Doesn't appear to capture running video correctly. It instead just freezes to pevious screen and updating to a blank screen near the end of captures.

**Comment by negativetwelve** [comment]
Hi @wookelvin, are these issues with UX Cam itself? or specifically with this module?

Have you been able to run the native libraries without this react-native specific layer?

**Comment by wookelvin** [comment]
I have not been able to isolate the issues between the native library and the react-native layer.

**Comment by negativetwelve** [comment]
Thanks for the information, this sounds like a UXCam issue with the native library rather than the small wrapper that this module provides around the native portion. I don't work for UXCam, I just created this module because it was missing from the community and I wanted the ability to use UXCam on my react-native project. Your best bet is to contact support for UXCam, sorry :(

@richardgroves might be able to help as he works at UXCam

**Comment by negativetwelve** [comment]
Going to close this as it's an issue with the native library and not the react-native wrapper. You can definitely continue discussion via this issue if you'd like!
