### ISSUE TITLE
previousScreen rendering everytime rather than splashScreen in IOS

### ISSUE THREAD

**Issue by MaheshNandam** [negativetwelve/react-native-ux-cam#55]
react -  16.0.0
react-native - 0.50.4
react-native-ux-cam - 4.4.0

When I'm sending the uxcam key from the router, the last visited page was rendering every time before the splash screen, can you address this issue?

@negativetwelve

**Comment by MaheshNandam** [comment]
hey @negativetwelve, please address this issue!

**Comment by negativetwelve** [comment]
Hi @MaheshNandam, this issue is most likely not caused by the react-native-ux-cam module.

It is either caused by UXCam itself, or some conflict with your navigation library. Without an example project to see the issue, I'm afraid I cannot help you figure this one out. It seems very specific to your use case / project.

**Comment by VishwajeetDagar** [comment]
I am also facing the same issue even with the react native sample project. I just started using react-native-ux-cam with the sample project and encountered this issue. Using react-native version 0.59.2
