### ISSUE TITLE
Screen recordings not showing any text or images

### ISSUE THREAD

**Issue by gregkerzhner** [negativetwelve/react-native-ux-cam#96]
This is an example of a recording generated by react-native-ux-cam.  There are no text and no images, so its not very useful.   Are there known workarounds for this bug?
![wtf](https://user-images.githubusercontent.com/2031812/65082278-610c7080-d95a-11e9-9e9c-48292866543e.gif)

**Comment by gregkerzhner** [comment]
The screen recordings are working on Android though - so I know its not a necessarily a setup issue on my part.

**Comment by antpuleo2586** [comment]
I'm also experiencing this, no assets showing up. On latest version 5.1.10 and React Native version 0.60.4

**Comment by igor-lemon** [comment]
I have the same issue. But I don't know is it ok or not :D

**Comment by jmderueda** [comment]
Same here, any workarounds on this?

**Comment by antpuleo2586** [comment]
After speaking to the guys at UXCam, it seems this is disabled by default on iOS due to privacy concerns. You supposedly need to sign an agreement stating that you're not sending any sensitive data, before UXCam will enable this.
In other words, use calls such as `RNUxcam.occludeSensitiveView(view)` to hide certain elements that will contain sensitive information.

Maybe someone can confirm this though?

**Comment by fang0rnz** [comment]
Same here, any news?

**Comment by richardgroves** [comment]
Sorry for the delay - the latest plugin (5.1.13) has just been released as a full version rather than beta. That includes the latest native SDK (3.1.9) that has much improved schematic capture for react-native.

If you have specific view types that are still not being captured, or being badly captured, please open a support issue with our team and we can work to include those as well.

**Comment by meTech1021** [comment]
Hello @richardgroves 

I am experiencing an issue with react-native-ux-cam (version ^6.0.8) where the content of React Native modals and bottom drawers is not being recorded.

I have implemented the standard setup and tested it, but the recordings do not capture these UI elements. Could you please advise on how to resolve this or if there is a recommended workaround?

Thank you for your assistance.

**Comment by richardgroves** [comment]
Hi @meTech1021 ,

Sorry but I left UXCam about 5 years ago so can't help any longer. You probably need to contact their support to get help with this as it doesn't look like its been updated here for a long time.

Richard
